version: '3.8'
services: 
    backend:
      build:
        context: ./dataAnchor
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      depends_on: 
        - db
      
    db:
      image: redis:6
      restart: always
      ports: 
        - 6379:6379
      